# Generated by Django 4.0.4 on 2022-05-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('pass_word', models.CharField(max_length=100)),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.address')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_product', models.IntegerField(default=0)),
                ('total_price', models.FloatField()),
                ('status', models.BooleanField()),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.products')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
                ('product', models.TextField()),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
            ],
        ),
    ]
