# Generated by Django 4.0.4 on 2022-05-06 08:26

from django.db import migrations, models
import sale.models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=sale.models.upload_to),
        ),
    ]
