# Generated by Django 4.0.4 on 2022-05-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_products_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
    ]
