# Generated by Django 4.0.4 on 2022-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_history_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='product1',
            field=models.TextField(null=True),
        ),
    ]
