# Generated by Django 4.0.4 on 2022-05-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_history_product1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='product1',
            new_name='product',
        ),
    ]
