# Generated by Django 4.0.4 on 2022-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_rename_product1_history_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.TextField(),
        ),
    ]
