# Generated by Django 4.0.4 on 2022-05-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_history_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.address'),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number_product',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
