# Generated by Django 4.0.4 on 2022-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_alter_address_id_alter_customer_id_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
