# Generated by Django 4.0.4 on 2022-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_alter_address_id_alter_customer_id_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
