# Generated by Django 4.0.4 on 2022-06-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_alter_address_address_alter_products_id'),
        ('sale', '0008_remove_customer_id_address_customer_address_and_more'),
    ]

    operations = [
    ]
