# Generated by Django 4.0.5 on 2022-06-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_alter_customer_key_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
