# Generated by Django 4.0.4 on 2022-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
